### ISSUE TITLE
What's the algorithm implemented in this project, about making the gpr being incremental?

### ISSUE THREAD

**Issue by yuhui-xie** [jgosmann/goppy#2]

**Comment by yuhui-xie** [comment]
It seems that the updating time is not const
----------------------
When I execute:

start = time.time()
gp.add(x2, y2)
end = time.time()
print(end - start)

start = time.time()
gp.add(x2, y2)
end = time.time()
print(end - start)
-------------------------
And I get:

3.900810480117798
4.391140937805176
-----------------------

**Comment by jgosmann** [comment]
No, the updating time is not constant, but of complexity `O(n * max(n², N²))` where `n` is the number of data points being added and `N` is the total number of data points added so far. Note that this is (asymptotically) still better than completely re-initializing the Gaussian Process which has a complexity of `O((n + N)³)` because of the matrix inversion necessary.

Further details can be found in [my Master thesis, Section 3.1](https://www.ki.tu-berlin.de//fileadmin/fg135/publikationen/Gosmann_2013_GPP.pdf).

**Comment by yuhui-xie** [comment]
> No, the updating time is not constant, but of complexity `O(n * max(n², N²))` where `n` is the number of data points being added and `N` is the total number of data points added so far. Note that this is (asymptotically) still better than completely re-initializing the Gaussian Process which has a complexity of `O((n + N)³)` because of the matrix inversion necessary.
> 
> Further details can be found in [my Master thesis, Section 3.1](https://www.ki.tu-berlin.de//fileadmin/fg135/publikationen/Gosmann_2013_GPP.pdf).

thank u !

**Comment by dandxy89** [comment]
@jgosmann - can you provide an alternative link to your Masters thesis? The link isn't working for me (cannot be found).

**Comment by jgosmann** [comment]
Sure: [thesis.pdf](https://github.com/jgosmann/goppy/files/11995181/thesis.pdf)
